#!/usr/bin/bash

set -eux

PATH=$PATH:/usr/sbin/
DATADIR="/var/lib/mysql"
MARIADB_PASSWORD=${MARIADB_PASSWORD:-"change_me"}
MARIADB_CONF_FILE="/etc/my.cnf.d/metal3.cnf"
MARIADB_CERT_FILE=/certs/mariadb/tls.crt
MARIADB_KEY_FILE=/certs/mariadb/tls.key
RESTART_CONTAINER_CERTIFICATE_UPDATED=${RESTART_CONTAINER_CERTIFICATE_UPDATED:-"false"}
USER="$(whoami)"
MARIADB_MAX_CONNECTIONS=${MARIADB_MAX_CONNECTIONS:-"64"}

mkdir -p "$(dirname "${MARIADB_CERT_FILE}")"
if [ -f "$MARIADB_CERT_FILE" ] && [ ! -f "$MARIADB_KEY_FILE" ] ; then
    echo "Missing TLS private key file ${MARIADB_KEY_FILE}"
    exit 1
fi
if [ ! -f "$MARIADB_CERT_FILE" ] && [ -f "$MARIADB_KEY_FILE" ] ; then
    echo "Missing TLS Certificate file ${MARIADB_CERT_FILE}"
    exit 1
fi

# Restart mysqld when the certificate is updated
if [[ -f "$MARIADB_CERT_FILE" && "${RESTART_CONTAINER_CERTIFICATE_UPDATED}" == "true" ]]; then
    # shellcheck disable=SC2034,SC2162
    inotifywait -m -e delete_self "${MARIADB_CERT_FILE}" | while read file event; do
        kill $(pgrep -f mysqld)
    done &
fi

if [ ! -d "${DATADIR}/mysql" ]; then
    cat > "$MARIADB_CONF_FILE" <<EOF
[mysqld]
max_connections = "${MARIADB_MAX_CONNECTIONS}"
max_heap_table_size = 1M
innodb_buffer_pool_size = 5M
innodb_log_buffer_size = 512K
user = "${USER}"
log_warnings = 4
EOF

    # Config MariaDB to enable TLS
    if [ -f "$MARIADB_CERT_FILE" ]; then
        cat >> "$MARIADB_CONF_FILE" <<EOF
ssl
ssl_cert = ${MARIADB_CERT_FILE}
ssl_key = ${MARIADB_KEY_FILE}
EOF
    fi

    mysql_install_db --datadir="$DATADIR" --skip-test-db --user="${USER}" --group="${USER}"

    cat > /tmp/configure-mysql.sql <<-EOSQL
DELETE FROM mysql.user ;
CREATE USER 'ironic'@'localhost' identified by '${MARIADB_PASSWORD}' ;
GRANT ALL on *.* TO 'ironic'@'localhost' WITH GRANT OPTION ;
DROP DATABASE IF EXISTS test ;
CREATE DATABASE IF NOT EXISTS  ironic ;
FLUSH PRIVILEGES ;
EOSQL

    exec mysqld --init-file /tmp/configure-mysql.sql --skip-log-error
else
    exec mysqld --skip-log-error
fi
